# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca58fd83ab68a83f1059ffb9aabb1e93a34a6745d8c38495d715d99fa023a9e69d4479a1d634b4c289ca4e29c69dc685b79b5e3307bcef435bfc7a80c7171292

test:
  secret_key_base: 0e22e4bfcc91d7ab4eda14de51c871792ce9c42f86aadf1607e2700d162d7514e9cc29bcc3fbf89d56009f2fbdf457ec0ce6dbb58a3f85228d1ac9552d09d655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
